### ISSUE TITLE
Bee AI

### ISSUE THREAD

**Issue by the10thWiz** [the10thWiz/ScrapWorld#5]
Create an AI for bees (e.g. Flying), which should just move toward the player.

Please use the PhysicsController to handle collisions:
- Bee AI depends on PhysicsController, and get the PhysicsController in the start method
- In update, calculate movement direction, then call controller.Move(velocity) to move the bee

**Comment by ZedeV2** [comment]
But we have the melee ai already bro

**Comment by the10thWiz** [comment]
I create this issue before I adapted the melee ai to the bee.
